### PR TITLE
Add conda as a dependency of minirhumba

### PR DESCRIPTION
**Pull request by marimeireles**

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Why is conda needed?

**Comment by marimeireles** [comment]
Because when I tried the linux version on my linux ` bash minirhumba-0.0.1-Linux-x86_64.sh` I got
```
minirhumba-0.0.1-Linux-x86_64.sh: line 408: /home/mariana/minirhumba/bin/conda: No such file or directory
      
```
:(
@SylvainCorlay

**Comment by SylvainCorlay** [comment]
> minirhumba-0.0.1-Linux-x86_64.sh

hum, we should probably patch the constructor so that it does not require conda in the generated shell script.

**Comment by marimeireles** [comment]
I don't think... I know how to do that.

**Comment by marimeireles** [comment]
@wolfv said it'd be good to wait for the monstructor. Cause then, we'd use the conda that was laying around instead of demanding an exclusive one for rhumba. I think it's a good idea.

**Comment by SylvainCorlay** [comment]
Sure, although I think the fix may be reasonable.

**Pull request merged**
